

user_embedding:
  - user_id_embedding
  - cms_segid_embedding
user_dense: 
  - cms_group_id_indicator
  - final_gender_code_indicator
  - age_level_indicator
  - pvalue_level_indicator
  - shopping_level_indicator
  - occupation_indicator
  - new_user_class_level_indicator

item_embedding:
  - adgroup_id_embedding
  - cate_id_embedding
  - customer_id_embedding
  - campaign_id_embedding
  - brand_id_embedding
item_dense:
  - pid_indicator
  - price_numeric

fm_input_layer:
  - user_embedding
  - item_embedding
dnn_input_layer:
  - user_embedding
  - user_dense
  - item_embedding
  - item_dense

embedding_size: 10
dnn_hidden_layers: [512, 256, 128]

